### ISSUE TITLE
Composer Package missing

### ISSUE THREAD

**Issue by sgtpenguin** [carlcs/craft-helpers#1]
Hello.  Tried to install via composer today, got the following message:

```
Problem 1
    - Installation request for carlcs/craft-helpers ^1.3 -> satisfiable by carlcs/craft-helpers[v1.3.0].
    - carlcs/craft-helpers v1.3.0 requires urodoz/truncate-html dev-getgravfixes -> no matching package found.
```

I have minimum stability to 'dev'

**Comment by carlcs** [comment]
Oh, thanks for the notice, I totally fogot about fixing this. Should work now: https://github.com/carlcs/craft-helpers/releases

**Comment by sgtpenguin** [comment]
Perfect.  Thank You!
